export const gibraltarAreaList = [
    { label: 'South District' },
    { label: 'Town District' },
    { label: 'Marina District' },
    { label: 'East & North District' },
    { label: 'Westside District' },
    { label: 'Admirals Place' },
    { label: 'Anchorage' },
    { label: 'Arengos Garden' },
    { label: 'Atlantic Suites' },
    { label: 'Bayview Terraces' },
    { label: 'Both Worlds' },
    { label: 'Brympton' },
    { label: 'Buena Vista Park Villas' },
    { label: 'Catalan Bay' },
    { label: 'Clemence Suites' },
    { label: 'Clifftop House' },
    { label: 'Comorant Wharf' },
    { label: 'Cumberland Place' },
    { label: 'Cumberland Terraces' },
    { label: 'Eaton Park' },
    { label: 'Elliots Battery' },
    { label: 'Europlaza' },
    { label: 'Filomena House' },
    { label: 'Gardiners Road' },
    { label: 'Gardiners View' },
    { label: 'Genista House' },
    { label: 'Harbour Views' },
    { label: 'Jumpers Building' },
    { label: 'Kings Wharf - Quay 27' },
    { label: 'Kings Wharf - Quay 29' },
    { label: 'Lord Napier Mews' },
    { label: 'MaidaVale Mews' },
    { label: 'Marina Bay' },
    { label: 'Marina Court' },
    { label: 'Marina Views' },
    { label: 'Merlot House' },
    { label: 'MidTown' },
    { label: 'Montagu Crescent' },
    { label: 'Montagu Gardens' },
    { label: 'Nelsons View' },
    { label: 'Northview Terrace' },
    { label: 'Ocean Heights' },
    { label: 'Ocean Village - Grand' },
    { label: 'Ocean Village - Imperial' },
    { label: 'Ocean Village - Leisure Island' },
    { label: 'Ocean Village - Majestic' },
    { label: 'Ocean Village - Mews' },
    { label: 'Ocean Village - Ocean Spa Plaza' },
    { label: 'Ocean Village - Royal' },
    { label: 'Ordnance Wharf' },
    { label: 'Peninsular Heights' },
    { label: 'Plata Villa' },
    { label: 'Portland House' },
    { label: 'Prince Edward\'s Gate' },
    { label: 'Queensway Quay' },
    { label: 'Rock Gardens' },
    { label: 'Rosbay Court' },
    { label: 'Rosia Court' },
    { label: 'Rosia Dale' },
    { label: 'Rosia Plaza' },
    { label: 'Sandpit Mews' },
    { label: 'Shackleton House' },
    { label: 'Sir William Jackson Grove' },
    { label: 'Sunnyside House' },
    { label: 'Sunrise View' },
    { label: 'Sunset Close' },
    { label: 'Tarik Views' },
    { label: 'The Arches' },
    { label: 'The Cliftons' },
    { label: 'The Island' },
    { label: 'The Sails' },
    { label: 'Town Area' },
    { label: 'Town Area - Upper' },
    { label: 'Tradewinds' },
    { label: 'Trafalgar House' },
    { label: 'Victoria Residency' },
    { label: 'Vineyards' },
    { label: 'Watergardens' },
    { label: 'Waterport Place' },
    { label: 'Waterport Terraces' },
    { label: 'Wellington Court' },
    { label: 'West One' },
    { label: 'Westview Park' },
    { label: 'World Trade Center' },
]

export const spainAreaList = [
    { label: 'Alcaidesa' },
    { label: 'Algeciras' },
    { label: 'Bahia de las Rocas' },
    { label: 'Campamento' },
    { label: 'Canos de Meca' },
    { label: 'Casares' },
    { label: 'Casares Costa' },
    { label: 'Castellar de la Frontera' },
    { label: 'Chiclana' },
    { label: 'Duquesa' },
    { label: 'El Cuarton' },
    { label: 'Elviria, Marbella' },
    { label: 'Estepona' },
    { label: 'Guadacorte' },
    { label: 'Guadiaro' },
    { label: 'Hacienda Guadalupe' },
    { label: 'Jimena' },
    { label: 'Jimena de la Frontera' },
    { label: 'La Linea de la Concepcion' },
    { label: 'La Paloma (between Duquesa and Sotogrande)' },
    { label: 'Los Barrios' },
    { label: 'Manilva' },
    { label: 'Manilva Beach' },
    { label: 'Manilva Costa' },
    { label: 'Marbella' },
    { label: 'Mijas Costa' },
    { label: 'Pueblo Nueva Guadiaro' },
    { label: 'Puente Mayorga' },
    { label: 'Punta Chullera' },
    { label: 'Sabinillas' },
    { label: 'San Martin del Tesorillo' },
    { label: 'San Pablo' },
    { label: 'San Roque' },
    { label: 'Santa Margarita' },
    { label: 'Sotogrande' },
    { label: 'Sotogrande Port' },
    { label: 'Torreguadiaro' },
    { label: 'Zahara de los Atunes' },
]
